language: objective-c
osx_image: xcode10
xcode_workspace: Shadowsocks.xcworkspace
xcode_scheme: Shadowsocks
before_install:
  - pod install
script:
  - set -o pipefail && CODE_SIGNING_ALLOWED=NO xcodebuild -workspace Shadowsocks.xcworkspace -scheme Shadowsocks clean test | xcpretty
